### ISSUE TITLE
[Feature Request]: allow additional body content in body prop for <RemoveModal>

### ISSUE THREAD

**Issue by aknguyen7** [carbon-design-system/ibm-products#5838] opened 2024-08-08 17:42 UTC
### The problem

am using <RemoveModal> from https://ibm-cloud.slack.com/archives/C2K6RFJ1G/p1723128447589299?thread_ts=1723126954.620389&cid=C2K6RFJ1G and would like to have 2 separate line of text content inside the body for example

```
Removing bx1001 will permanently remove the configuration. This action cannot be undone.

Are you sure you want to delete this?
```

right now it's look like this

```
Removing bx1001 will permanently remove the configuration. This action cannot be undone. Are you sure you want to delete this?`
```

### The solution

provide the capability to allow more than one line of text in the body

### Design link

https://ibm-cloud.slack.com/archives/C2K6RFJ1G/p1723128447589299?thread_ts=1723126954.620389&cid=C2K6RFJ1G

### Links to other materials

![image](https://github.com/user-attachments/assets/638577d5-73fa-494d-8835-3342814ba492)

### Owner/main maintainer(s)

David Menendez

### Business priority

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by davidmenendez** [comment] 2024-08-08 18:08
i don't see anywhere in the [usage guidelines](https://pages.github.ibm.com/cdai-design/pal/patterns/removing/code/) that prohibits additional body content, but since it seems like it's supposed to be minimal i think we should just get design feedback before opening up the `body` prop to accept nodes in addition to strings.

**Comment by devadula-nandan** [comment] 2024-08-09 08:40
could be duplicate of #2289

**Comment by davidmenendez** [comment] 2024-08-09 12:54
resolved via https://github.com/carbon-design-system/ibm-products/pull/5792

**Closed by davidmenendez** 2024-08-09 12:54 UTC
Labels: status: duplicate, status: needs triage 🕵️‍♀️, needs: design opinion
