### ISSUE TITLE
Data grid filtering rows === losing nested rows

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/ibm-products#4978] opened 2024-04-24 10:59 UTC
### Package

Carbon for IBM Products

### Description

When removing filters rows do not always come back.

### Component(s) impacted

Datagrid

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

v2.34.0

### Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Product/offering

App Engine

### CodeSandbox or Stackblitz example

https://stackblitz.com/edit/github-6w6hhw-ieejed?file=package.json

### Steps to reproduce the issue (if applicable)

1. Filter by anything e.g. `bus`
2. Close the filter dialog
3. Click clear filters
4. Note some nested rows do not return.
5. Open the filter dialog, note one is still selected.
6. Clearing it does not restore the missing rows.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by elycheea** [comment] 2024-05-13 14:38
Closing as duplicate of #4652

**Closed by elycheea** 2024-05-13 14:38 UTC
Labels: status: needs triage 🕵️‍♀️
