### ISSUE TITLE
[Datagrid] - Nested rows in Datagrid is broken in React 17

### ISSUE THREAD

**Issue by jeesonjohnson** [carbon-design-system/ibm-products#5995] opened 2024-09-03 12:51 UTC
### Package

Carbon for IBM Products

### Description

When using nestedRows within the DataGrid component in React 17, the application crashes on expansion of the rows. We think that this was introduced in the release `2.48.0`. The error that we see can be seen below: 

```
Uncaught Error: Cell(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
    at reconcileChildFibers2 (/node_modules/.vite/deps/chunk-HAIV5P5B.js?v=88ffb8f4:10932:29)
    at reconcileChildren (/node_modules/.vite/deps/chunk-HAIV5P5B.js?v=88ffb8f4:13095:37)
    at mountIndeterminateComponent (/node_modules/.vite/deps/chunk-HAIV5P5B.js?v=88ffb8f4:13724:13)
    at beginWork (/node_modules/.vite/deps/chunk-HAIV5P5B.js?v=88ffb8f4:14497:22)
    at HTMLUnknownElement.callCallback2 (/node_modules/.vite/deps/chunk-HAIV5P5B.js?v=88ffb8f4:3899:22)
    at Object.invokeGuardedCallbackDev (/node_modules/.vite/deps/chunk-HAIV5P5B.js?v=88ffb8f4:3924:24)
    at invokeGuardedCallback (/node_modules/.vite/deps/chunk-HAIV5P5B.js?v=88ffb8f4:3958:39)
    at beginWork$1 (/node_modules/.vite/deps/chunk-HAIV5P5B.js?v=88ffb8f4:17658:15)
    at performUnitOfWork (/node_modules/.vite/deps/chunk-HAIV5P5B.js?v=88ffb8f4:16881:20)
    at workLoopSync (/node_modules/.vite/deps/chunk-HAIV5P5B.js?v=88ffb8f4:16835:13)
```

This is a mission critical error, as users are not able to use the nestedRows on React17. This causes our whole app to crash. 

### Component(s) impacted

DataGrid component

### Browser

Chrome, Safari, Firefox, Microsoft Edge

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.48.0

### Suggested Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Product/offering

IBM Cloud Pak for Integration (CP4I)

### CodeSandbox or Stackblitz example

See [Here](https://codesandbox.io/p/devbox/youthful-tree-wh8r45?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm0m4vg6f00083b6myiqkin6g%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm0m4vg6f00033b6mkfi5487c%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm0m4vg6f00053b6m7fnkamdy%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm0m4vg6f00073b6m39tqr89k%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm0m4vg6f00033b6mkfi5487c%2522%253A%257B%2522id%2522%253A%2522cm0m4vg6f00033b6mkfi5487c%2522%252C%2522activeTabId%2522%253A%2522cm0metjro004l3b6m26q0uydc%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0m4vg6f00023b6mhb3kj7nk%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FExample%252FExample.jsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.codesandbox%252Ftasks.json%2522%252C%2522id%2522%253A%2522cm0metjro004l3b6m26q0uydc%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522cm0m4vg6f00073b6m39tqr89k%2522%253A%257B%2522id%2522%253A%2522cm0m4vg6f00073b6m39tqr89k%2522%252C%2522activeTabId%2522%253A%2522cm0m4vk2l00103b6m5jqsq1dt%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0m4vg6f00063b6m6jipsyv9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A5173%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522cm0m4vk2l00103b6m5jqsq1dt%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522cm0m4vg6f00053b6m7fnkamdy%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm0m4vg6f00043b6m39j7m7h4%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522cm0m4vg6f00053b6m7fnkamdy%2522%252C%2522activeTabId%2522%253A%2522cm0m4vg6f00043b6m39j7m7h4%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce the issue (if applicable)

Go to the codesandbox. Expand out all the expandable rows. The app should crash. See video for example in React 17.

https://github.com/user-attachments/assets/da401f7f-62d4-4f3d-8070-2d9f072da57a

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by sean-anderson-ibm** [comment] 2024-09-04 15:56
This is also broken with react 16.

**Comment by matthewgallo** [comment] 2024-09-04 16:23
This is a duplicate of https://github.com/carbon-design-system/ibm-products/issues/5986, but the bits about this occurring in previous react versions is very helpful. I've created a reproduction and will look at this. See @flannanl's workaround in #5986 until we address this further.

https://stackblitz.com/edit/github-gkxha8?file=package.json,src%2Fmain.jsx,src%2FExample%2FExample.jsx

**Closed by matthewgallo** 2024-09-04 16:23 UTC
Labels: status: needs triage 🕵️‍♀️
