### ISSUE TITLE
Sass Depreciation warning introduced in v2.47.0

### ISSUE THREAD

**Issue by richardpilot** [carbon-design-system/ibm-products#5887] opened 2024-08-19 11:15 UTC
### Package

Carbon for IBM Products

### Description

After migrating to 2.47.0, the following error is now reported in our builds.
```<w> Deprecation This operation is parsed as:
<w> 
<w>     ($i % list.length($colors)) + 1
<w>
<w> but you may have intended it to mean:
<w>
<w>     ($i % list.length($colors)) (+1)
<w>
<w> Add a space after + to clarify that it's meant to be a binary operation, or wrap
<w> it in parentheses to make it a unary operation. This will be an error in future
<w> versions of Sass.
<w>
<w> More info and automated migrator: https://sass-lang.com/d/strict-unary
<w>
<w> null
<w> Deprecation This operation is parsed as:
<w>
<w>     (($item-index - 1) % $group-colors-length) + 1
<w>
<w> but you may have intended it to mean:
<w>
<w>     (($item-index - 1) % $group-colors-length) (+1)
<w>
<w> Add a space after + to clarify that it's meant to be a binary operation, or wrap
<w> it in parentheses to make it a unary operation. This will be an error in future
<w> versions of Sass.
<w>
<w> More info and automated migrator: https://sass-lang.com/d/strict-unary
<w>
<w> null
```

This is most likely caused by the modification to the ConditionBuild scss
https://github.com/carbon-design-system/ibm-products/pull/5762/files#diff-53f4d09c6fe30a389079ce97e44123ac8586efffe6a7ef2858556d2388200851

### Component(s) impacted

ibm-products: 2.47.0

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

v2.47.0

### Suggested Severity

None

### Product/offering

MQ

### CodeSandbox or Stackblitz example

N/A

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by amal-k-joy** [comment] 2024-08-19 13:30
closing as this is duplicate of #5835

**Closed by amal-k-joy** 2024-08-19 13:30 UTC
Labels: status: needs triage 🕵️‍♀️
