### ISSUE TITLE
[TagSet]: Unable to remove tag from TagSet modal 

### ISSUE THREAD

**Issue by artikandri** [carbon-design-system/ibm-products#5267] opened 2024-05-20 13:09 UTC
### Package

Carbon for IBM Products

### Description

I was using the TagSet component with the following data structure: 
[
   { label: "test", type: "gray", filter: true, onClick: removeFilter() }
]

Everything works well until I applied more than 100 tags to this component and want to see all tags and remove some of the tags with the help of the modal.

Expectation: The x (close) button in each tag inside the modal should be rendered

What happened: no x (close) button rendered  

### Component(s) impacted

TagSet

<img width="1728" alt="Screenshot 2024-05-20 at 15 06 25" src="https://github.com/carbon-design-system/ibm-products/assets/12537724/fa038e1e-c944-4816-9d69-9731011cfa1a">

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.19.2

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Product/offering

Cloud pak for data 

### CodeSandbox or Stackblitz example

https://codesandbox.io/p/devbox/zealous-mirzakhani-vnnhjp

### Steps to reproduce the issue (if applicable)

1. Import TagSet 
2. Use TagSet with > 10 data and the filter option enabled (the example uses 100 data) 
3. Use all properties related to allTagsModal... to show the modal 
4. Open the modal 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by elycheea** [comment] 2024-05-20 13:52
Closing as duplicate of #4358

**Closed by elycheea** 2024-05-20 13:52 UTC
Labels: status: needs triage 🕵️‍♀️
