### ISSUE TITLE
Upgrading @carbon/react to 1.57 causes infinite loop in Datagrid (

### ISSUE THREAD

**Issue by lee-chase** [carbon-design-system/ibm-products#5403] opened 2024-06-04 15:18 UTC
### Package

Carbon for IBM Products

### Description

Updating my prototype to Carbon/React 1.57.0 causes an infinite loop in the datagrid.

If I comment out this it works.
`<FilterFlyout {...getFilterFlyoutProps()} />`

### Component(s) impacted

Datagrid

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.41.0

### Severity

Severity 1 = The design is broken in a critical way that blocks users from completing tasks or damages the brand. Affects major functionality, no workaround.

### Product/offering

N/A

### CodeSandbox or Stackblitz example

N/A

### Steps to reproduce the issue (if applicable)

Internal prototype link can be provided for investigation.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by matthewgallo** [comment] 2024-06-06 18:13
Hey @lee-chase, are you using the `MultiSelect` filter by chance? I am able to replicate this bug after upgrading Carbon, but only if the `MultiSelect` filter is being used in either the filter panel or flyout. Just trying to narrow this down.

**Comment by matthewgallo** [comment] 2024-06-06 18:29
Could you also share what filters you're including in the flyout? If you could provide a code sandbox/stackblitz even better 😄

**Comment by matthewgallo** [comment] 2024-06-18 17:24
Stems from https://github.com/carbon-design-system/carbon/issues/16469 which looks to be resolved. I'll update our version of `@carbon/react` when this fix has been included in a release.

**Comment by elycheea** [comment] 2024-06-19 14:19
Moving this to sprint 21 for now to try to time the next `@carbon/react` version + next dependency updates.

**Comment by Ashley-Johnson28** [comment] 2024-07-03 14:52
Do we know a timeline when the data grid will be fixed? Our team is hoping to implement the filter flyout with multi select with our newest feature and could be blocked by this.

**Comment by matthewgallo** [comment] 2024-07-03 16:08
Hey @Ashley-Johnson28, we've been waiting for a new release from `@carbon/react` as the root cause here was from the `MultiSelect` component. I've opened a [draft PR](https://github.com/carbon-design-system/ibm-products/pull/5643) to use the latest version that will fix this issue. With the upcoming holiday my guess is that it will be reviewed/merged next week.

**Closed** 2024-07-10 20:14 UTC
Labels: component: Datagrid, Sev 1, role: dev
