### ISSUE TITLE
[Native tooltip in DataGrid's cell]: Tooltip is not shown for custom component in v2.45.0

### ISSUE THREAD

**Issue by rcsatheeshkumar** [carbon-design-system/ibm-products#5830] opened 2024-08-08 07:02 UTC
### Package

Carbon for IBM Products

### Description

In version 2.43.1,  in the DataGrid component when we render an icon as a custom component in the cell, the string value provided in the row data for that header would be shown as native tooltip when hovered over the icon. However in version 2.45.0, the tooltip is not being shown.

### Component(s) impacted

In version 2.43.1 we see that tooltip is shown when hovered over the icon in the table cell as shown below. But not in version 2.45.0 tooltip is not shown 

![TooltipVisible](https://github.com/user-attachments/assets/1d4a8e74-ee4b-4de3-9ad7-289895202f9d)

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.45.0

### Suggested Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Product/offering

Financial Transaction Manager

### CodeSandbox or Stackblitz example

https://stackblitz.com/edit/github-t1gly7?file=package-lock.json,src%2FExample%2FExample.jsx

### Steps to reproduce the issue (if applicable)

In the table, hover over the Person icon in the "First name" column to see the tooltip. It won't appear. However in this stackblitz -https://stackblitz.com/edit/github-pi2pvg?file=src%2FExample%2FExample.jsx,package.json - which uses version 2.43.1 we could see the tooltip. 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by AlexanderMelox** [comment] 2024-08-08 14:47
Hello @rcsatheeshkumar , we have a workaround for this. Please use the Carbon `Tooltip` component instead.

**Comment by szymonbrandys** [comment] 2024-08-09 10:56
I agree that tooltips for icons, links, and other similar elements can be handled on our end using Carbon tooltips as you suggested. However, for table headers, labels, overflow menu items, and the like, we need to display a tooltip only when the text is truncated and shown with an ellipsis.

I'm aware that some apps heavily rely on this behavior, as it was a mandatory requirement during accessibility testing. It's important to note that the tooltip should not be displayed constantly but only when Carbon truncates the text.

**Comment by AlexanderMelox** [comment] 2024-08-09 14:19
Re-opening issue to address this when truncation is needed

**Comment by davidmenendez** [comment] 2024-08-19 14:19
hey @rcsatheeshkumar thanks for reaching out with your concern!

this is actually working as intended. the recent change on our end was done to address accessibility issues within datagrid. unnecessary `title` attributes were removed from cells and other parts of the component. if you need a tooltip you can implement the cell structure with a carbon tooltip on your end. if you have any questions feel free to reach out.

closing and marking issue as complete.

**Closed by davidmenendez** 2024-08-19 14:19 UTC
Labels: status: needs triage 🕵️‍♀️

**Comment by davidmenendez** [comment] 2024-08-19 14:29
@szymonbrandys as a follow up to your comments: most of these concerns should be handled on the consumer end. with regards to `DataGrid`, because it has a lot of column width interaction functionality ellipsis can be handled by readjusting the width. this is considered to be an acceptable accessibility action. now days, most accessibility experts recommend not using ellipsis or any form of truncation that hides content from the screen at all. as you've mentioned though it is unfortunately bound to happen, but the solution is still not to add `title` attributes all over the table. any place you are concerned about introducing truncation you should consider incorporating a carbon `Tooltip` component.

**Comment by szymonbrandys** [comment] 2024-08-19 20:29
@davidmenendez so you are saying that if the text in a cell or header is truncated, one way to meet accessibility requirements is to allow users to manually widen the column? In other words, users can drag the column boundary to view the full content, making a tooltip unnecessary. Is that correct?
