### ISSUE TITLE
Cannot find module 'lottie-web' from 'node_modules/@carbon/ibm-products/lib/components/SteppedAnimatedMedia/SteppedAnimatedMedia.js'

### ISSUE THREAD

**Issue by xmannyxfreshx1** [carbon-design-system/ibm-products#3987] opened 2023-12-21 20:23 UTC
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.

Using latest version of ibm-products, our jest based test fail with the following errror `Cannot find module 'lottie-web' from 'node_modules/@carbon/ibm-products/lib/components/SteppedAnimatedMedia/SteppedAnimatedMedia.js'`

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to
> see changed?

From versions 2.17.1 to 2.18.1 the package worked as expect and tests were not failing.
Version 2.19.0 builds and run fine, it's just causing jest tests to fail.

> What browser are you working in?

Chrome

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

`"@carbon/ibm-products": "2.19.0",`

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

> Please create a reduced test case in CodeSandbox
>
> https://codesandbox.io/s/github/carbon-design-system/ibm-products/tree/main/examples/carbon-for-ibm-products/SidePanel

## Additional information

- Screenshots or code
- Notes

**Comment by xmannyxfreshx1** [comment] 2023-12-21 20:29
Additional info:
We are not using the affected component - `InlineTip`
We already have use `jest-canvas-mock` in our jest.config

**Comment by elycheea** [comment] 2023-12-22 17:12
Duplicate of #3352 which we reopened after Dominik’s report yesterday.

**Comment by paul-balchin-ibm** [comment] 2024-01-02 17:38
Hi, a new release was just built to deal with this specific issue. 

Please try installing version `@carbon/ibm-products` version `2.19.2`.

**Comment by xmannyxfreshx1** [comment] 2024-01-03 15:32
@paul-balchin-ibm Thank you for the updated version. The new version `2.19.2` resolves the jest test error mentioned in the issue. 👍🏽

**Comment by paul-balchin-ibm** [comment] 2024-01-03 15:58
Thanks for verifying @xmannyxfreshx1!

And thanks to @matthewgallo for the fix 👍

**Closed by paul-balchin-ibm** 2024-01-03 15:58 UTC
Labels: dependencies, v2, status: waiting for author 💬

**Comment by matthewgallo** [comment] 2024-01-03 16:03
That was all @elycheea! 🥇

**Comment by xmannyxfreshx1** [comment] 2024-01-03 17:43
Thanks @elycheea!
