### ISSUE TITLE
Datagrid `useSelectRows` does not work with `useNestedRows` extension

### ISSUE THREAD

**Issue by flannanl** [carbon-design-system/ibm-products#4300] opened 2024-02-09 14:39 UTC
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.
When using `useSelectedRows` with `useNestedRows`, clicking a nested row will actually select a different row at the root level. After inspecting the code in `useSelectRows`, the current logic that generate the `rowId` is not correct. It never takes into account when a row is nested inside another row, in which case its `index` is only "unique" inside that nested level.

```
const rowId = `${tableId}-${row.index}`;
```

> Is this issue related to a specific component?
Datagrid

> What did you expect to happen? What happened instead? What would you like to
> see changed?
The ID of the checkbox input must be unique. With the current logic, it breaks a11y and also screws the row selection with nested rows in the table.

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?
`v1.70.0`. However, I see the same issue with `v2`.

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
IBM Cloud Projects

## Steps to reproduce the issue

Create a Datagrid table with both `useSelectRows` and `useNestedRows`.

> Please create a reduced test case in CodeSandbox
>
> https://codesandbox.io/s/github/carbon-design-system/ibm-products/tree/main/examples/carbon-for-ibm-products/SidePanel

## Additional information

- Screenshots or code

![useSelectedRows](https://github.com/carbon-design-system/ibm-products/assets/12156672/5f2a5f97-2e1f-4154-ae49-9f37887804d6)
![useSelectedRows](https://github.com/carbon-design-system/ibm-products/assets/12156672/887a3dae-4af7-4934-9620-184a5935fa5b)

**Comment by flannanl** [comment] 2024-02-09 14:40
cc @hoiwingh

**Comment by matthewgallo** [comment] 2024-02-09 14:41
Hey @flannanl, this seems to be a duplicate of https://github.com/carbon-design-system/ibm-products/issues/3887

**Comment by flannanl** [comment] 2024-02-09 14:45
@matthewgallo Probably. I think mine points out a more specific issue with the current logic. I don't mind you mark this or the other duplicate as long as you can fix the issue I pointed out. Thanks.

**Comment by matthewgallo** [comment] 2024-02-09 15:16
Ok, lets keep this one open as well. @Ratheeshrajan, can you review any notes here from @flannanl that may not be documented in https://github.com/carbon-design-system/ibm-products/issues/3887?

**Comment by flannanl** [comment] 2024-02-12 14:00
@matthewgallo Is there an ETA when this will get fixed?

**Comment by matthewgallo** [comment] 2024-02-12 14:36
@Ratheeshrajan is assigned to it for the current sprint (Feb 8 - 21), we can be sure to post any updates on this issue as it's being worked on.

**Comment by hoiwingh** [comment] 2024-02-12 22:56
@matthewgallo - if I change the row ID computation to the following it works for me:
```
var rowId = "".concat(tableId, "-").concat(row?.original?.id).concat(row.index);
```

Not entirely sure if `row.orginal.id` is guaranteed to exist but just a FYI.

**Comment by elycheea** [comment] 2024-02-22 13:41
Closing as duplicate of #3887

**Closed by elycheea** 2024-02-22 13:41 UTC
Labels: component: Datagrid
