### ISSUE TITLE
[Bug]: Carbon for IBM Products: Datagrid - When "Row settings" is selected as medium or small and left open, when the screen is resized, the last options are not visible

### ISSUE THREAD

**Issue by PinceGitHub** [carbon-design-system/ibm-products#5925] opened 2024-08-22 12:58 UTC
### Package

Carbon for IBM Products

### Description

When "Row settings" is selected as medium or small and left open, when the screen is resized, the last options are not visible.

**Stackblitz:** https://stackblitz.com/edit/github-uzudxy?file=src%2FApp.jsx,package.json

**Screenshot:**
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/c185e30a-f89f-48f9-96e8-7b15e50ca9bc">

**Recording**
https://github.com/user-attachments/assets/9040d8a1-4785-4443-b24b-1b330c58bb8f

### Component(s) impacted

**Stackblitz:** https://stackblitz.com/edit/github-uzudxy?file=src%2FApp.jsx,package.json

**Screenshot:**
<img width="1728" alt="image" src="https://github.com/user-attachments/assets/c185e30a-f89f-48f9-96e8-7b15e50ca9bc">

**Recording**
https://github.com/user-attachments/assets/9040d8a1-4785-4443-b24b-1b330c58bb8f

### Browser

Chrome, Firefox, Microsoft Edge

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

"@carbon/ibm-products": "^2.45.0"

### Suggested Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Product/offering

IBM FTM

### CodeSandbox or Stackblitz example

https://stackblitz.com/edit/github-uzudxy?file=src%2FApp.jsx,package.json

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by jakubkloc** [comment] 2024-09-05 10:00
Can you estimate when this issue will be resolved?

**Comment by amal-k-joy** [comment] 2024-09-20 05:47
Hi @jakubkloc ,
This is an expected behaviour of Carbon modals when `scrollHeight > clientHeight` . This happens when you resize while keeping the Row settings popover open and the height of the container is too low.  Could you tackle this by setting a minimum height for your container or resize after closing the Row settings popover ?

<img width="605" alt="image" src="https://github.com/user-attachments/assets/3e7f5b8c-8b3f-41cf-b451-3e309a00cd80">

**Comment by jakubkloc** [comment] 2024-09-27 18:44
Thanks for response @amal-k-joy,
We can't assume that users always closing Row setting before resizing also better to avoid interference with default modals sizing behavior (this could disturb the layout of the entire page).

I think the best solution would be to add to this component, property like  ```autoAlign``` in Combo Box from carbon, to display this Row settings menu over the container.

**Comment by amal-k-joy** [comment] 2024-10-07 15:44
> Thanks for response [@amal-k-joy](https://github.com/amal-k-joy), We can't assume that users always closing Row setting before resizing also better to avoid interference with default modals sizing behavior (this could disturb the layout of the entire page).
> 
> I think the best solution would be to add to this component, property like `autoAlign` in Combo Box from carbon, to display this Row settings menu over the container.

Hi @jakubkloc ,
Here we are using carbon popovers. I think `autoAlign` feature is still under expirimental from carbon. We have this [issue](https://github.com/carbon-design-system/carbon/issues/17670) to track this.

**Comment by PinceGitHub** [comment] 2024-10-11 04:17
@amal-k-joy Could you please confirm your proposed solution? Providing a minimum height to the modal is not a good idea because it will affect the layout. I look forward to hearing from you.

**Comment by matthewgallo** [comment] 2024-10-14 14:39
I agree, using `autoAlign` on the popover should allow the menu to not be cut off. We can try to put together an example for you to look at.

**Comment by amal-k-joy** [comment] 2024-10-22 10:37
> I agree, using `autoAlign` on the popover should allow the menu to not be cut off. We can try to put together an example for you to look at.
Hi @matthewgallo ,
Looks like  carbon has addressed the issues in  `autoAlign`  for popovers in latest version(1.68.0). So we can fix this issue by exposing 'autoAlign' for this popover in Datagrid.

**Closed** 2024-10-30 10:16 UTC
Labels: type: bug 🐛, component: Datagrid, Sev 3, role: dev

**Comment by PinceGitHub** [comment] 2024-11-05 09:41
@amal-k-joy Could you help confirm which version of Carbon for IBM Products I should use in order to receive this fix?
