### ISSUE TITLE
Color of exclamation mark in the status icon gets lighter as the size decreases

### ISSUE THREAD

**Issue by fbarroso24** [carbon-design-system/ibm-products#1913] opened 2022-04-13 15:43 UTC
## Title line template: [Title]: 
Color of exclamation mark in the status icon gets lighter as the size decreases
![image](https://user-images.githubusercontent.com/8657768/163218372-85a187c4-3274-4cc3-9b4a-c5249e26800f.png)

## What package(s) are you using?
"@carbon/ibm-products": "1.13.0"
- [ ] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> Describe in detail the issue you're having.
Regarding the [Status Icon](https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-patterns-status-icons-statusicon--default&args=kind:major-warning) component, the color of the exclamation mark gets lighter as the size of the icon gets smaller.  This behavior is also observed in the story book.  See 1st screenshot of the progression from sm->md->lg->xlg . 
![image](https://user-images.githubusercontent.com/8657768/163217600-86c574c6-844e-4452-b029-01f4e925ac6e.png)

The [spec](https://pages.github.ibm.com/cdai-design/pal/patterns/status-icons/usage/)  (2nd screenshot) says the light and dark themes for the major-warning icon should be the same regardless of light or dark theme but doesn't mention anything about the exclamation point progressively getting darker.  
![image](https://user-images.githubusercontent.com/8657768/163217708-9893cb93-d9b4-4c29-873c-2af36303ad1c.png)

```
       <StatusIcon
	        iconDescription='low score'
	        kind='major-warning'
	        size='sm'
	        theme='light'
        />
```

> Is this issue related to a specific component?
Yes the `StatusIcon` component

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?
Chrome 100.0.4896.88

> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?
"@carbon/ibm-products": "1.13.0"

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
OpenPages

## Steps to reproduce the issue
It is reproducible on the storybook online
https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-patterns-status-icons-statusicon--default&args=kind:major-warning
## Additional information

- Screenshots or code
- Notes

**Comment by fbarroso24** [comment] 2022-07-13 15:41
@AlexanderMelox any updates on this one? Thanks in advance!

**Comment by paul-balchin-ibm** [comment] 2024-01-10 16:19
The source of the problem is not that the assigned colors are changing as the icon gets smaller.

The problem is the browser’s rendering engine. To provide smoother, cleaner graphics, the engine uses _anti-aliasing_ to “smooth” adjacent pixels to reduce “jagged edges”. 

![image](https://github.com/carbon-design-system/ibm-products/assets/52505287/505e9ccd-4726-487b-b233-14feb5f99247)

As an example, I enlarged your screenshot. Notice how, as the icon gets smaller and smaller, the rendering doesn’t just “smooth” the shape of the exclamation point, but also the difference between the orange and black colors. 

Anti-aliasing is a great feature for producing smoother images and icons, but the penalty is that small details will lose both definition and color.

This is something that cannot be fixed by web developers.

![image](https://github.com/carbon-design-system/ibm-products/assets/52505287/37e6e9af-807e-4da8-86ea-3d432dd25dd8)

**Closed** 2024-01-10 16:25 UTC
Labels: type: bug 🐛, status: won’t fix 🔚, good first issue 🌱
