### ISSUE TITLE
Unable to use ibm-products plugin with react v18.2.0

### ISSUE THREAD

**Issue by vijaygpatil04** [carbon-design-system/ibm-products#3200] opened 2023-07-12 15:26 UTC
## What package(s) are you using?

- [SidePanel] Carbon for IBM Products

## Detailed description

> Describe in detail the issue you're having.
We are exploring the use of @carbon/ibm-products in our project. As of now, we are interested in using SidePanel component.
We have a hard dependency on React v18.2.0. With this React version, SidePanel component is throwing following error -

[ERROR] Missing "./jsx-runtime.js" specifier in "react" package [plugin vite:dep-pre-bundle]

    node_modules/react-dnd/dist/esm/core/DndProvider.mjs:28:28:
      28 │ import { jsx as _jsx } from "react/jsx-runtime.js";
         ╵                             ~~~~~~~~~~~~~~~~~~~~~~

  This error came from the "onResolve" callback registered here:

    node_modules/esbuild/lib/main.js:1282:20:
      1282 │       let promise = setup({
           ╵                     ^

    at setup (file:///D:/RhapsodyDev/sysml-test/node_modules/vite/dist/node/chunks/dep-210e5610.js:39852:19)
    at handlePlugins (D:\RhapsodyDev\sysml-test\node_modules\esbuild\lib\main.js:1282:21)
    at buildOrContextImpl (D:\RhapsodyDev\sysml-test\node_modules\esbuild\lib\main.js:971:5)
    at Object.buildOrContext (D:\RhapsodyDev\sysml-test\node_modules\esbuild\lib\main.js:779:5)
    at D:\RhapsodyDev\sysml-test\node_modules\esbuild\lib\main.js:2175:68
    at new Promise (<anonymous>)
    at Object.context (D:\RhapsodyDev\sysml-test\node_modules\esbuild\lib\main.js:2175:27)
    at Object.context (D:\RhapsodyDev\sysml-test\node_modules\esbuild\lib\main.js:2015:58)
    at prepareEsbuildOptimizerRun (file:///D:/RhapsodyDev/sysml-test/node_modules/vite/dist/node/chunks/dep-210e5610.js:45866:35)

> Is this issue related to a specific component?
SidePanel

> What browser are you working in?
Chrome

> What version of the @carbon/ibm-products package are you using?
v2.3.2

## Steps to reproduce the issue

1. Open the following SidePanel example shared by ibm-products component - https://codesandbox.io/p/sandbox/github/carbon-design-system/ibm-products/tree/main/examples/carbon-for-ibm-products/SidePanel?file=%2Fsrc%2FExample%2FExample.jsx
2. Open package.json file
3. Update version of react and react-dom to 18.2.0
4. Use yarn install command load the plugins
5. Use yarn dev command to start the application
6. You should see following error in the console -
[ERROR] Missing "./jsx-runtime.js" specifier in "react" package [plugin vite:dep-pre-bundle]
    node_modules/react-dnd/dist/esm/core/DndProvider.mjs:28:28:
      28 │ import { jsx as _jsx } from "react/jsx-runtime.js";

**Comment by elycheea** [comment] 2023-07-12 17:43
This is in progress. The work is in PR but we’re continuing to update our tests for the update.
https://github.com/carbon-design-system/ibm-products/pull/3146

Duplicate of #2895

**Closed by elycheea** 2023-07-12 17:43 UTC
Labels: type: bug

**Comment by SunnyJohal** [comment] 2023-07-24 21:35
If you really wanted to use it with react 18 in your vite setup you would need to do the following:

In your `package.json` file add an overrides property, something like this:

```
"overrides": {
    "@carbon/ibm-products": {
        "react": "^18.2.0",
        "react-dom": "^18.2.0"
    },
}
```

Then in your vite config add the relevant aliases:

```
  resolve: {
    alias: {
      '~@carbon': '@carbon',
      '~@ibm': '@ibm',
      'react/jsx-runtime.js': 'react/jsx-runtime',
    },
  },
```

That will get it working, but you might notice some inconsistencies with jumpy animations etc
