### ISSUE TITLE
[Tagset]: visual bug in hundreds of tags modal

### ISSUE THREAD

**Issue by davidmenendez** [carbon-design-system/ibm-products#5917] opened 2024-08-21 18:05 UTC
### Package

Carbon for IBM Products

### Description

<img width="866" alt="Screenshot 2024-08-21 at 12 58 56 PM" src="https://github.com/user-attachments/assets/0d7421d2-3e32-4606-b534-1c3032a5b242">

the bottom gradient isn't being properly applied.

### Component(s) impacted

`Tagset` and possibly other components utilizing a carbon modal with `hasScrollingContent`

### Browser

Chrome

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

2.47

### Suggested Severity

Severity 3 = The problem is visible or noticeable to users but does not impede the usability or functionality. Affects minor functionality, has a workaround.

### Product/offering

2.47

### CodeSandbox or Stackblitz example

https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-tag-set-tagset--hundreds-of-tags&globals=viewport:basic

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by elycheea** [comment] 2024-08-23 18:07
Wait, I already have a PR for this but there was a fix from Core around the same time that might have changed my fix. https://github.com/carbon-design-system/ibm-products/pull/4478

Duplicate of #4359 so I’ll close this one and add that one back to a future sprint?

**Closed by elycheea** 2024-08-23 18:07 UTC
Labels: status: needs triage 🕵️‍♀️, UX: visual

**Comment by davidmenendez** [comment] 2024-08-23 20:42
sounds good. thanks!
