### ISSUE TITLE
After update to 2.42.0 receiving 'Uncaught Error: Unable to find a feature flag with the name: `default-portal-target-body`'

### ISSUE THREAD

**Issue by schuetza** [carbon-design-system/ibm-products#5473] opened 2024-06-12 07:02 UTC
### Package

Carbon for IBM Products

### Description

Just updated my dependencies 

    "@carbon/ibm-products": "2.42.0",
    "@carbon/react": "1.58.1",

Now, when initializing Tearsheet, I just get  

```
Uncaught Error: Unable to find a feature flag with the name: `default-portal-target-body`
    checkForFlag index.js:332
    enabled index.js:419
    useFeatureFlag index.js:111
    usePortalTarget usePortalTarget.js:15
    node_modules devLayer.41d8d78e.js:2774
```

### Component(s) impacted

Tearsheet

### Browser

Firefox

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

"@carbon/ibm-products": "2.42.0",

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Product/offering

CP4BA as a Service

### CodeSandbox or Stackblitz example

https://stackblitz.com/github/carbon-design-system/ibm-products/tree/main/examples/carbon-for-ibm-products/Tearsheet?file=src%2FExample%2FExample.jsx

### Steps to reproduce the issue (if applicable)

Just open the code sandbox above and open console.
Circumvention: Step back to 2.41.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by matthewgallo** [comment] 2024-06-12 10:40
Hi @schuetza, this is a duplicate of https://github.com/carbon-design-system/ibm-products/issues/5468 and is resolved in `2.42.1-canary.3`.

**Closed by matthewgallo** 2024-06-12 10:40 UTC
Labels: status: needs triage 🕵️‍♀️
