### ISSUE TITLE
[Datagrid]: Filtering with nested rows does not work as expected

### ISSUE THREAD

**Issue by flannanl** [carbon-design-system/ibm-products#5443] opened 2024-06-10 14:50 UTC
### Package

Carbon for IBM Products

### Description

There are a few issues with filtering / search capability with nested rows in Datagrid. This can be easily reproducible with the storybook example: https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-nestedrows--single-level-nested-rows-usage-story.

Using the storybook example:
1) If I search for a string appearing in the parent row, I see only the parent row to appear. I would expect the children rows should be appeared as well since they are part of the hierarchy.
2) Continue from (1) above, if I clear the search text, I would expect the filtered children rows to reappear, but they do not. Those children rows are simply lost and I have no way to bring them back unless I do a page reload on the storybook example.
3) If I search for a string appearing only in the children row, I am not seeing that row appeared in the filtered results. I would expect I will see the filtered rows in the children rows with its parent showing up.

### Component(s) impacted

This is an issue with Datagrid component. And here are some screenshots of what I have tried.

1) First and second issue:
- Start with the following Datagrid rows
![image](https://github.com/carbon-design-system/ibm-products/assets/12156672/a8fccb13-3eb3-4c3a-9d88-437f61718e92)

- Enter "weight" in the filter search box. Only the parent row appears. Would expect the children to be there as well.
![image](https://github.com/carbon-design-system/ibm-products/assets/12156672/044e6349-3aee-4594-9b06-b770f2691ca7)

- Clear "weight" from the filter search box. Now the children rows from the "weight" row are not gone.
![image](https://github.com/carbon-design-system/ibm-products/assets/12156672/64e759d3-6da5-4219-8bd2-67a892247ea6)

2) Third issue:
- Start with the following Datagrid rows
![image](https://github.com/carbon-design-system/ibm-products/assets/12156672/a5ad3a67-08de-47ec-87e6-84b30a860946)

- Enter "shade" in the filter search box. Nothing appear in the table. Would expect the first parent row with its child row containing the "shade" text to appear in the table.
![image](https://github.com/carbon-design-system/ibm-products/assets/12156672/585555f7-6065-44cf-a080-353ee31359c3)

### @carbon/ibm-products (previously @carbon/ibm-cloud-cognitive) version

v1.73.1

### Severity

Severity 2 = Aspects of design is broken, and impedes users in a significant way, but there is a way to complete their tasks. Affects major functionality, has a workaround.

### Product/offering

IBM Cloud Projects

### CodeSandbox or Stackblitz example

https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-components-datagrid-nestedrows--single-level-nested-rows-usage-story&globals=viewport:basic

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/ibm-products/blob/main/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/ibm-products/issues) for duplicate issues

**Comment by matthewgallo** [comment] 2024-06-10 15:09
Hey @flannanl, this sounds like a duplicate of https://github.com/carbon-design-system/ibm-products/issues/4652. Can you confirm? Thanks!

**Comment by flannanl** [comment] 2024-06-10 15:13
@matthewgallo I think the core problem is the same. But mine requests for a behavioural change to the filtering as well, which I think it's not fully related to the core problem.

**Comment by filipmadejIBM** [comment] 2024-06-19 12:51
We experience same issue, search doesn't work for nested rows.

**Comment by davidmenendez** [comment] 2024-06-27 14:26
for design consideration: how [add & select](https://carbon-for-ibm-products.netlify.app/?path=/story/ibm-products-patterns-add-and-select-multiaddselect--with-hierarchy&globals=viewport:basic) works when filtering

**Comment by matthewgallo** [comment] 2024-07-24 21:02
This seems to be a similar issue that was reported in #4652, see the appropriate fix [here](https://github.com/carbon-design-system/ibm-products/issues/4652#issuecomment-2166494571).

**Closed by matthewgallo** 2024-07-24 21:02 UTC
Labels: type: enhancement ✨, needs: design opinion, component: Datagrid, version: 2, role: dev
