### ISSUE TITLE
[Datagrid] using useSortableColumns and useCustomizeColumns hooks together breaks column customization.

### ISSUE THREAD

**Issue by xmannyxfreshx1** [carbon-design-system/ibm-products#2837] opened 2023-04-06 14:49 UTC
## What package(s) are you using?

- [x] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description 

> Describe in detail the issue you're having.

Using useSortableColumns and useCustomizeColumns hooks together breaks column customization. Both work fine independently but when trying to use both at the same time, the column customization tearsheet fails to populate the columns. Sorting works independently or combined.

> Is this issue related to a specific component?

Datagrid

> What did you expect to happen? What happened instead? What would you like to
> see changed?

The exception is for both hooks to work in harmony 😄  

> What browser are you working in?

Chrome
> What version of the @carbon/ibm-products (or @carbon/ibm-cloud-cognitive)
> package are you using?

`"@carbon/ibm-products": "1.47.0",`
> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

CP4WAIOps

## Steps to reproduce the issue

1. Step one:
Load a datagrid and enable either `useSortableColumns` or  hooks and notice they work as expected
2. Step two
Use both hooks at the same time, then notice the columns are not customizable anymore.

> Please create a reduced test case in CodeSandbox
>
> https://codesandbox.io/s/github/carbon-design-system/ibm-cloud-cognitive/tree/main/examples/cloud-cognitive/codesandbox

https://codesandbox.io/s/angry-stallman-muehg2?file=/src/Example/Example.js

## Additional information

- Screenshots or code
### Datagrid with both hooks enabled
![Screenshot 2023-04-06 at 10 46 08 AM](https://user-images.githubusercontent.com/13371221/230415680-e0e126c9-92b6-4287-b0de-6be11e2748b6.png)

### Datagrid with just `useCustomizeColumns` enabled
![Screenshot 2023-04-06 at 10 48 22 AM](https://user-images.githubusercontent.com/13371221/230416118-bb4944a0-ae6b-44e5-888f-b21f6467be2b.png)

- Notes

**Comment by K-Markopoulos** [comment] 2023-05-04 07:59
The `useCustomizeColumns` doesn't work with `useColumnCenterAlign` hook.  If the latter is present and `centerAlignedColumn` is set for a column, this column won't be displayed in the Customize Columns tearsheet.

To reproduce add `useColumnCenterAlign` and the following column:
```
  {
    Header: 'First Name',
    accessor: 'firstName',
    centerAlignedColumn: true,
  }
```

The column doesn't pass the following filter since `centerAlignedColumn` prop makes colDef.Header a function.

https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/cfaefc9db5475ea66248757847f0330beb4b9f5c/packages/ibm-products/src/components/Datagrid/Datagrid/addons/CustomizeColumns/DraggableItemsList.js#L33-L40

I thought it makes sense to address this case under this issue, as well. Please let me know if I should create a separate issue.

**Comment by elycheea** [comment] 2023-07-06 17:06
@K-Markopoulos If this is still an issue, can we open this as a new issue. :)

**Comment by matthewgallo** [comment] 2023-08-15 14:26
Waiting to close until #3348 is merged.

**Closed** 2023-08-15 16:32 UTC
Labels: type: bug, component: Datagrid
