### ISSUE TITLE
Datagrid "select all" checkbox and toolbar action are not working on paged rows

### ISSUE THREAD

**Issue by alvin-ibm** [carbon-design-system/ibm-products#4757] opened 2024-04-05 13:16 UTC
## What package(s) are you using?

- [X] Carbon for IBM Products (or Carbon for IBM Cloud & Cognitive)
- [ ] Legacy/CDAI
- [ ] Legacy/Security

## Detailed description

> If the `Datagrid `has multiple pages, checking the "select all" checkbox or selecting a row then "Select all" on the toolbar action throws an error.

https://github.com/carbon-design-system/ibm-products/assets/140297065/56d9b7c1-b24f-441d-9926-4cb10b2e5438

> What version of the @carbon/ibm-products 
> package are you using? **v2.34.0**

> What offering/product do you work on? Envizi ESG

## Steps to reproduce the issue

1. Populate a datagrid with records that will be paginated
2. Check the "select all" checkbox on the header row
Or
2. Select a row
3. Click the "Select all" toolbar action

## Additional information

- Issue can be simulated on this story https://ibm-products.carbondesignsystem.com/?path=/story/ibm-products-components-datagrid-rowactionbuttons--row-action-buttons-batch-actions-usage-story

**Comment by matthewgallo** [comment] 2024-04-05 13:27
Hey @alvin-ibm, I believe this is a duplicate of https://github.com/carbon-design-system/ibm-products/issues/4748 which @davidmenendez is looking into.

**Comment by davidmenendez** [comment] 2024-04-05 19:13
this should be fixed in #4763

**Closed by davidmenendez** 2024-04-05 19:13 UTC
